var TIME_ONE_SECOND = 1000;
var TIME_ONE_MINUTE = TIME_ONE_SECOND * 60;
var TIME_ONE_HOUR   = TIME_ONE_MINUTE * 60;
var TIME_ONE_DAY    = TIME_ONE_HOUR * 24;
//***********
var LOGIN_TIMES = "LoginTimes";
///----------- DAILY REWARDS CONSTANTS
var TIME_FOR_ONE_REWARD = TIME_ONE_DAY ; //0.4 * TIME_ONE_MINUTE;
var LAST_TIME_DAILY_REWARD = "DailyRewardLastTime";
var TOTAL_NUMBER_REWARD_DAYS = 15;
////---------- TEAMS AND TOURNAMENTS CONSTANTS
var TOURNAMENT_DURATION = TIME_ONE_DAY;

var TEMPORAL_CODE_GIFT_50DIAMONDS = "IDLESUNsssssDAaaaaaY";
